void polText(){
  tMes = "Моїй коханій Зайченяткі";
  tNow = "teraz";
  tPress = "mmHg";
  tSpeed = "m/s";
  tMin = "min.";
  tTom = "Jutro";
  tKurs = "Kurs Privat24";
  tSale = "Wymiana";
  tYour = "Twój";
  tPoint = "Polacz sie z punktem dostępu WiFi-Clock i wprowadz w przeglądarce adres: 192.168.4.1         ";
  tJanuary = "stycznia";
  tFebruary = "lutego";
  tMarch = "marzca";
  tApril = "kwiecnia";
  tMay = "maja";
  tJune = "czerwca";
  tJuly = "lipca";
  tAugust = "sierpnia";
  tSeptember = "wrzesnia";
  tOctober = "pazdziernika";
  tNovember = "listopada";
  tDecember = "grudznia";
  tMonday = "Poniedzialek";
  tTuesday = "Wtorek";
  tWednesday = "Środa";
  tThursday = "Czwartek";
  tFriday = "Piątek";
  tSaturday = "Sobota";
  tSunday = "Niedziela";
  tClearSky = "czyste niebo";
  tSkyIsClear = "niebo jest jasne";
  tFewClouds = "kilka chmur";
  tScatteredClouds = "rozproszone chmury";
  tBrokenClouds = "rozbite chmury";
  tOvercastClouds = "ciezkie chmury";
  tLightRain = "lekki deszcz";  
  tModerateRain = "umiarkowany deszcz";
  tLightIntensityShowerRain = "lekka intensywność deszczów";
  tShowerRain="ulewa";
  tHeavyIntensityRain = "silna intensywność deszczów";
  tVeryHeavyRain = "bardzo ulewny deszcz";
  tThunderstorm = "burza";
  tHaze = "mgła";
  tFog = "mgła";
  tMist = "zamglenie";
  tShowerSleet = "deszcz ze śniegiem";
  tLightSnow = "lekki śnieg";
  tLightShowerSnow = "lekkie opady śniegu"; 
  tSnow = "śnieg";
  tWeatrNot = "   Brak aktualizacji pogody przez ponad 6 godzin!!!   ";
  tWeatrTN = "brak aktualizacji pogody - ";
  
  printTime();
  Serial.println("Text POL.");
}
