void ukrText(){
  tMes = "Моїй коханій Зайченяткі";
  tNow = "зараз";
  tPress = "ммРс";
  tSpeed = "м/с";
  tMin = "хв.";
  tTom = "Завтра";
  tKurs = "Курс Privat24";
  tSale = "Куп/Прод.";
  tYour = "Ваш";
  tPoint = "Підключіться до точки доступу WiFi-Clock і введіть в браузері адресу: 192.168.4.1       ";
  tJanuary = "січня";
  tFebruary = "лютого";
  tMarch = "березня";
  tApril = "квітня";
  tMay = "травня";
  tJune = "червня";
  tJuly = "липня";
  tAugust = "серпня";
  tSeptember = "вересня";
  tOctober = "жовтня";
  tNovember = "листопада";
  tDecember = "грудня";
  tMonday = "Понеділок";
  tTuesday = "Вівторок";
  tWednesday = "Середа";
  tThursday = "Четвер";
  tFriday = "П'ятниця";
  tSaturday = "Субота";
  tSunday = "Неділя";
  tClearSky = "чисте небо";
  tSkyIsClear = "ясне небо";
  tFewClouds = "малохмарно";
  tScatteredClouds = "розірвані хмари";
  tBrokenClouds = "хмарно з проясненнями";
  tOvercastClouds = "дужа хмарність";
  tLightRain = "невеликий дощ";
  tModerateRain = "помірний дощ";
  tLightIntensityShowerRain = "легка інтесивність дощів";
  tShowerRain = "злива";
  tHeavyIntensityRain = "сильна інтенсивність дощів";
  tVeryHeavyRain = "дуже сильний дощ";
  tThunderstorm = "гроза";
  tHaze = "туман";
  tFog = "туман";
  tMist = "густий туман";
  tShowerSleet = "сніг з дощем";
  tLightSnow = "легкий сніг";
  tLightShowerSnow = "невеликий снігопад"; 
  tSnow = "сніг";
  tWeatrNot = "   Немає оновлень погоди більше 6 годин!!!   ";
  tWeatrTN = "немає оновлень погоди - ";
  
  printTime();
  Serial.println("Text UKR.");

}
